name: test-suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nix-tests:
    name: Run nix tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Check Nix Flake
        run: |
          nix flake check

      - name: Run Tests
        run: |
          nix run '.#tests'


  cross-platform-tests:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Rust build
        run: |
          cd rust
          cargo build

      - name: Rust tests
        run: |
          cd rust
          cargo test --all-targets

      - name: Clojure tests
        run: |
          cd clj
          export PATH=../rust/target/debug:$PATH
          clojure -X:test


  check-jarfile:
    name: Check jarfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Build and install jarfile locally
        run: |
          VERSION=$(grep '^version' rust/Cargo.toml | head -1 | cut -d'"' -f2)
          cd clj
          clojure -T:build install

      - name: Print version from jarfile
        run: |
          VERSION=$(grep '^version' rust/Cargo.toml | head -1 | cut -d'"' -f2)
          # this must run *outside* of the clj directory, so we're not relying on its deps.edn for dependency resolution
          clojure -Sdeps "{:mvn/local-repo \"$(pwd)/target/m2\" :deps {io.github.tesujimath/limabean-harvest {:mvn/version \"$VERSION\"}}}" -M -m limabean.harvest.main --version >VERSION
          cat VERSION
          test "$(cat VERSION)" == "limabean-harvest.clj $VERSION"
